apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapiargocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapiargocd
  template:
    metadata:
      labels:
        app: webapiargocd
    spec:
      containers:
      - name: webapiargocd
        image: cloudconnecthub/webapiargocd:1.0
        ports:
        - containerPort: 80
